/**
 * Magic Diet — seed data
 * Sources: IFCT-2017 (foods), NIN-2024 guidelines
 * Stub seed: ~30 foods, ~10 recipes, ~40 substitutions
 * Run: npx ts-node prisma/seed-diet.ts
 */
import { PrismaClient } from '@prisma/client';
import { PrismaMariaDb } from '@prisma/adapter-mariadb';

const adapter = new PrismaMariaDb(process.env.DATABASE_URL as string);
const prisma = new PrismaClient({ adapter } as any);

// ===================== FOODS =====================
const FOODS = [
  // CEREALS & MILLETS
  {
    id: 'food-rice-raw',
    name: 'White Rice (raw)',
    category: 'CEREAL_MILLET',
    vegType: 'VEGAN',
    kcalPer100g: 356, proteinGPer100g: 6.8, carbGPer100g: 78.2, fatGPer100g: 0.5,
    fiberGPer100g: 0.2, sodiumMgPer100g: 5, potassiumMgPer100g: 115,
    giIndex: 72, defaultPortionG: 80, defaultPortionDesc: '1/2 cup dry',
    mealSlots: ['lunch', 'dinner'],
    diseaseRestricted: ['diabetes_t2', 'pre_diabetes'],
    costTier: 'economy', prepTimeMin: 20,
    source: 'IFCT-2017',
  },
  {
    id: 'food-brown-rice',
    name: 'Brown Rice (raw)',
    category: 'CEREAL_MILLET',
    vegType: 'VEGAN',
    kcalPer100g: 350, proteinGPer100g: 7.9, carbGPer100g: 73.1, fatGPer100g: 2.7,
    fiberGPer100g: 3.5, sodiumMgPer100g: 4, potassiumMgPer100g: 250,
    giIndex: 55, defaultPortionG: 80, defaultPortionDesc: '1/2 cup dry',
    mealSlots: ['lunch', 'dinner'],
    diseaseAllowed: ['diabetes_t2', 'pre_diabetes', 'pcos'],
    costTier: 'standard', prepTimeMin: 35,
    source: 'IFCT-2017',
  },
  {
    id: 'food-wheat-atta',
    name: 'Whole Wheat Flour (atta)',
    category: 'CEREAL_MILLET',
    vegType: 'VEGAN',
    kcalPer100g: 341, proteinGPer100g: 12.1, carbGPer100g: 69.4, fatGPer100g: 1.7,
    fiberGPer100g: 1.9, sodiumMgPer100g: 2, potassiumMgPer100g: 284,
    giIndex: 54, defaultPortionG: 40, defaultPortionDesc: '1 medium roti',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    costTier: 'economy', prepTimeMin: 10,
    source: 'IFCT-2017',
  },
  {
    id: 'food-bajra',
    name: 'Pearl Millet (bajra)',
    category: 'CEREAL_MILLET',
    vegType: 'VEGAN',
    kcalPer100g: 361, proteinGPer100g: 11.6, carbGPer100g: 67.5, fatGPer100g: 5.0,
    fiberGPer100g: 1.2, ironMgPer100g: 8.0, calciumMgPer100g: 42,
    giIndex: 55, defaultPortionG: 40, defaultPortionDesc: '1 bajra roti',
    mealSlots: ['breakfast', 'dinner'],
    diseaseAllowed: ['diabetes_t2', 'anaemia'],
    costTier: 'economy', prepTimeMin: 15, seasonality: [10, 11, 12, 1, 2, 3],
    source: 'IFCT-2017',
  },
  {
    id: 'food-oats',
    name: 'Rolled Oats',
    category: 'CEREAL_MILLET',
    vegType: 'VEGAN',
    kcalPer100g: 389, proteinGPer100g: 16.9, carbGPer100g: 66.3, fatGPer100g: 6.9,
    fiberGPer100g: 10.6, sodiumMgPer100g: 2, potassiumMgPer100g: 362,
    giIndex: 55, defaultPortionG: 40, defaultPortionDesc: '1/3 cup dry',
    mealSlots: ['breakfast', 'mid_morning'],
    diseaseAllowed: ['diabetes_t2', 'high_ldl', 'heart_health', 'weight_loss'],
    costTier: 'standard', prepTimeMin: 5,
    source: 'IFCT-2017',
  },
  // PULSES & LEGUMES
  {
    id: 'food-toor-dal',
    name: 'Toor Dal (split pigeon pea)',
    category: 'PULSE_LEGUME',
    vegType: 'VEGAN',
    kcalPer100g: 335, proteinGPer100g: 22.3, carbGPer100g: 57.6, fatGPer100g: 1.7,
    fiberGPer100g: 15.0, ironMgPer100g: 6.7, potassiumMgPer100g: 1392,
    giIndex: 22, defaultPortionG: 30, defaultPortionDesc: '1 katori cooked',
    mealSlots: ['lunch', 'dinner'],
    fodmapLevel: 'moderate',
    diseaseAllowed: ['diabetes_t2', 'weight_loss', 'anaemia'],
    costTier: 'economy', prepTimeMin: 25,
    source: 'IFCT-2017',
  },
  {
    id: 'food-moong-dal',
    name: 'Moong Dal (split green gram)',
    category: 'PULSE_LEGUME',
    vegType: 'VEGAN',
    kcalPer100g: 334, proteinGPer100g: 24.5, carbGPer100g: 56.7, fatGPer100g: 1.2,
    fiberGPer100g: 8.2, ironMgPer100g: 4.4, calciumMgPer100g: 75,
    giIndex: 25, defaultPortionG: 30, defaultPortionDesc: '1 katori cooked',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    fodmapLevel: 'low',
    diseaseAllowed: ['diabetes_t2', 'ckd_early', 'weight_loss'],
    costTier: 'economy', prepTimeMin: 20,
    source: 'IFCT-2017',
  },
  {
    id: 'food-chickpeas',
    name: 'Chickpeas / Chana (cooked)',
    category: 'PULSE_LEGUME',
    vegType: 'VEGAN',
    kcalPer100g: 164, proteinGPer100g: 8.9, carbGPer100g: 27.4, fatGPer100g: 2.6,
    fiberGPer100g: 7.6, ironMgPer100g: 2.9, potassiumMgPer100g: 291,
    giIndex: 28, defaultPortionG: 100, defaultPortionDesc: '1 small katori',
    mealSlots: ['lunch', 'evening_snack', 'dinner'],
    fodmapLevel: 'moderate',
    diseaseAllowed: ['diabetes_t2', 'pcos', 'high_ldl'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  // DAIRY
  {
    id: 'food-curd',
    name: 'Curd (plain, full fat)',
    category: 'DAIRY',
    vegType: 'VEG',
    kcalPer100g: 98, proteinGPer100g: 3.1, carbGPer100g: 3.4, fatGPer100g: 4.3,
    fiberGPer100g: 0, calciumMgPer100g: 149, vitaminB12UgPer100g: 0.4,
    giIndex: 35, defaultPortionG: 150, defaultPortionDesc: '1 medium katori',
    mealSlots: ['lunch', 'evening_snack'],
    allergens: ['milk'],
    diseaseAllowed: ['diabetes_t2', 'ibs_c', 'pcos'],
    fodmapLevel: 'low',
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  {
    id: 'food-paneer',
    name: 'Paneer (cottage cheese)',
    category: 'DAIRY',
    vegType: 'VEG',
    kcalPer100g: 265, proteinGPer100g: 18.3, carbGPer100g: 1.2, fatGPer100g: 20.8,
    fiberGPer100g: 0, calciumMgPer100g: 208, sodiumMgPer100g: 40,
    giIndex: 25, defaultPortionG: 80, defaultPortionDesc: '2 medium cubes',
    mealSlots: ['breakfast', 'lunch', 'dinner', 'evening_snack'],
    allergens: ['milk'],
    diseaseAllowed: ['diabetes_t2', 'weight_loss', 'muscle_gain'],
    costTier: 'standard', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  {
    id: 'food-milk-toned',
    name: 'Toned Milk (1.5% fat)',
    category: 'DAIRY',
    vegType: 'VEG',
    kcalPer100g: 58, proteinGPer100g: 3.2, carbGPer100g: 4.8, fatGPer100g: 1.5,
    fiberGPer100g: 0, calciumMgPer100g: 120, vitaminB12UgPer100g: 0.3,
    giIndex: 40, defaultPortionG: 200, defaultPortionDesc: '1 glass',
    mealSlots: ['early_morning', 'breakfast', 'bedtime'],
    allergens: ['milk'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  // VEGETABLES
  {
    id: 'food-spinach',
    name: 'Spinach (palak)',
    category: 'GLV',
    vegType: 'VEGAN',
    kcalPer100g: 26, proteinGPer100g: 2.5, carbGPer100g: 3.7, fatGPer100g: 0.7,
    fiberGPer100g: 0.6, ironMgPer100g: 2.7, calciumMgPer100g: 99,
    vitaminAUgPer100g: 469, vitaminCMgPer100g: 28, folateUgPer100g: 194,
    giIndex: 15, defaultPortionG: 100, defaultPortionDesc: '1 katori cooked',
    mealSlots: ['lunch', 'dinner'],
    oxalateLevel: 2, // high oxalate — restrict for kidney stones
    diseaseAllowed: ['anaemia', 'heart_health', 'pregnancy'],
    diseaseRestricted: ['kidney_stone_oxalate'],
    vitaminKHighFlag: true,
    costTier: 'economy', prepTimeMin: 10, seasonality: [11, 12, 1, 2, 3],
    source: 'IFCT-2017',
  },
  {
    id: 'food-bitter-gourd',
    name: 'Bitter Gourd (karela)',
    category: 'VEGETABLE',
    vegType: 'VEGAN',
    kcalPer100g: 17, proteinGPer100g: 1.0, carbGPer100g: 3.7, fatGPer100g: 0.2,
    fiberGPer100g: 2.8, vitaminCMgPer100g: 88,
    giIndex: 14, defaultPortionG: 100, defaultPortionDesc: '1 katori cooked',
    mealSlots: ['lunch', 'dinner'],
    diseaseAllowed: ['diabetes_t2', 'pre_diabetes', 'weight_loss'],
    costTier: 'economy', prepTimeMin: 15,
    source: 'IFCT-2017',
  },
  {
    id: 'food-tomato',
    name: 'Tomato (ripe)',
    category: 'VEGETABLE',
    vegType: 'VEGAN',
    kcalPer100g: 20, proteinGPer100g: 0.9, carbGPer100g: 3.9, fatGPer100g: 0.2,
    fiberGPer100g: 1.2, vitaminCMgPer100g: 23, potassiumMgPer100g: 237,
    giIndex: 15, defaultPortionG: 100, defaultPortionDesc: '1 medium tomato',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    diseaseAllowed: ['diabetes_t2', 'heart_health', 'weight_loss'],
    diseaseRestricted: ['gerd'],
    costTier: 'economy', prepTimeMin: 5,
    source: 'IFCT-2017',
  },
  {
    id: 'food-broccoli',
    name: 'Broccoli',
    category: 'VEGETABLE',
    vegType: 'VEGAN',
    kcalPer100g: 34, proteinGPer100g: 2.8, carbGPer100g: 6.6, fatGPer100g: 0.4,
    fiberGPer100g: 2.6, vitaminCMgPer100g: 89, folateUgPer100g: 63,
    giIndex: 15, defaultPortionG: 100, defaultPortionDesc: '1 cup florets',
    mealSlots: ['lunch', 'dinner'],
    goitrogenFlag: true, // limit raw for hypothyroid
    diseaseAllowed: ['heart_health', 'weight_loss', 'cancer_support'],
    costTier: 'premium', prepTimeMin: 10,
    source: 'IFCT-2017',
  },
  // ROOT VEGETABLES
  {
    id: 'food-sweet-potato',
    name: 'Sweet Potato (shakarkand)',
    category: 'ROOT_TUBER',
    vegType: 'VEGAN',
    kcalPer100g: 86, proteinGPer100g: 1.6, carbGPer100g: 20.1, fatGPer100g: 0.1,
    fiberGPer100g: 3.0, vitaminAUgPer100g: 709, potassiumMgPer100g: 337,
    giIndex: 61, defaultPortionG: 100, defaultPortionDesc: '1 medium piece',
    mealSlots: ['breakfast', 'evening_snack'],
    diseaseAllowed: ['anaemia', 'pregnancy', 'weight_loss'],
    costTier: 'economy', prepTimeMin: 20, seasonality: [10, 11, 12, 1, 2],
    source: 'IFCT-2017',
  },
  {
    id: 'food-potato',
    name: 'Potato (boiled)',
    category: 'ROOT_TUBER',
    vegType: 'VEGAN',
    kcalPer100g: 87, proteinGPer100g: 1.9, carbGPer100g: 20.1, fatGPer100g: 0.1,
    fiberGPer100g: 1.8, potassiumMgPer100g: 379, vitaminCMgPer100g: 13,
    giIndex: 78, defaultPortionG: 100, defaultPortionDesc: '1 medium potato',
    mealSlots: ['lunch', 'dinner'],
    diseaseRestricted: ['diabetes_t2', 'pre_diabetes'],
    costTier: 'economy', prepTimeMin: 20,
    source: 'IFCT-2017',
  },
  // FRUITS
  {
    id: 'food-apple',
    name: 'Apple',
    category: 'FRUIT',
    vegType: 'VEGAN',
    kcalPer100g: 52, proteinGPer100g: 0.3, carbGPer100g: 13.8, fatGPer100g: 0.2,
    fiberGPer100g: 2.4, vitaminCMgPer100g: 4.6, potassiumMgPer100g: 107,
    giIndex: 36, defaultPortionG: 150, defaultPortionDesc: '1 medium apple',
    mealSlots: ['mid_morning', 'evening_snack'],
    diseaseAllowed: ['diabetes_t2', 'heart_health', 'high_ldl'],
    fodmapLevel: 'high',
    costTier: 'standard', prepTimeMin: 0, seasonality: [10, 11, 12, 1],
    source: 'IFCT-2017',
  },
  {
    id: 'food-banana',
    name: 'Banana (ripe)',
    category: 'FRUIT',
    vegType: 'VEGAN',
    kcalPer100g: 89, proteinGPer100g: 1.1, carbGPer100g: 22.8, fatGPer100g: 0.3,
    fiberGPer100g: 2.6, potassiumMgPer100g: 358, vitaminB12UgPer100g: 0,
    giIndex: 51, defaultPortionG: 120, defaultPortionDesc: '1 medium banana',
    mealSlots: ['early_morning', 'mid_morning', 'evening_snack'],
    diseaseAllowed: ['diarrhoea_recovery', 'pregnancy', 'anaemia'],
    diseaseRestricted: ['diabetes_t2'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  {
    id: 'food-guava',
    name: 'Guava',
    category: 'FRUIT',
    vegType: 'VEGAN',
    kcalPer100g: 68, proteinGPer100g: 2.6, carbGPer100g: 14.3, fatGPer100g: 1.0,
    fiberGPer100g: 5.4, vitaminCMgPer100g: 228, potassiumMgPer100g: 417,
    giIndex: 12, defaultPortionG: 100, defaultPortionDesc: '1 small guava',
    mealSlots: ['mid_morning', 'evening_snack'],
    diseaseAllowed: ['diabetes_t2', 'heart_health', 'anaemia', 'pregnancy'],
    costTier: 'economy', prepTimeMin: 0, seasonality: [10, 11, 12, 1, 2],
    source: 'IFCT-2017',
  },
  // FATS & OILS
  {
    id: 'food-ghee',
    name: 'Ghee (clarified butter)',
    category: 'FAT_OIL',
    vegType: 'VEG',
    kcalPer100g: 900, proteinGPer100g: 0, carbGPer100g: 0, fatGPer100g: 99.5,
    fiberGPer100g: 0, vitaminAUgPer100g: 1007,
    giIndex: 0, defaultPortionG: 5, defaultPortionDesc: '1 tsp',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    allergens: ['milk'],
    costTier: 'standard', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  {
    id: 'food-sunflower-oil',
    name: 'Sunflower Oil',
    category: 'FAT_OIL',
    vegType: 'VEGAN',
    kcalPer100g: 900, proteinGPer100g: 0, carbGPer100g: 0, fatGPer100g: 100,
    fiberGPer100g: 0,
    giIndex: 0, defaultPortionG: 10, defaultPortionDesc: '2 tsp',
    mealSlots: ['lunch', 'dinner'],
    diseaseRestricted: ['high_ldl'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  // NUTS & SEEDS
  {
    id: 'food-almonds',
    name: 'Almonds (badam)',
    category: 'NUT_OILSEED',
    vegType: 'VEGAN',
    kcalPer100g: 579, proteinGPer100g: 21.2, carbGPer100g: 21.6, fatGPer100g: 49.9,
    fiberGPer100g: 12.5, calciumMgPer100g: 264, ironMgPer100g: 3.7,
    giIndex: 0, defaultPortionG: 20, defaultPortionDesc: '6-8 almonds',
    mealSlots: ['early_morning', 'mid_morning', 'evening_snack'],
    allergens: ['tree_nuts'],
    diseaseAllowed: ['diabetes_t2', 'heart_health', 'high_ldl', 'weight_loss'],
    costTier: 'premium', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  {
    id: 'food-flaxseed',
    name: 'Flaxseed (alsi)',
    category: 'NUT_OILSEED',
    vegType: 'VEGAN',
    kcalPer100g: 534, proteinGPer100g: 18.3, carbGPer100g: 28.9, fatGPer100g: 42.2,
    fiberGPer100g: 27.3, omega3GPer100g: 22.8,
    giIndex: 35, defaultPortionG: 10, defaultPortionDesc: '1 tbsp ground',
    mealSlots: ['early_morning', 'breakfast'],
    diseaseAllowed: ['high_ldl', 'heart_health', 'pcos', 'constipation', 'ibs_c'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  // PROTEIN (non-veg)
  {
    id: 'food-egg',
    name: 'Egg (whole, boiled)',
    category: 'EGG',
    vegType: 'EGG',
    kcalPer100g: 155, proteinGPer100g: 13.0, carbGPer100g: 1.1, fatGPer100g: 11.0,
    fiberGPer100g: 0, vitaminB12UgPer100g: 1.1, vitaminDUgPer100g: 2.0,
    calciumMgPer100g: 56, ironMgPer100g: 1.75,
    giIndex: 0, defaultPortionG: 60, defaultPortionDesc: '1 large egg',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    allergens: ['egg'],
    diseaseAllowed: ['diabetes_t2', 'weight_loss', 'muscle_gain', 'anaemia'],
    costTier: 'economy', prepTimeMin: 10,
    source: 'IFCT-2017',
  },
  {
    id: 'food-chicken-breast',
    name: 'Chicken Breast (boneless, cooked)',
    category: 'FLESH_FOOD',
    vegType: 'NON_VEG',
    kcalPer100g: 165, proteinGPer100g: 31.0, carbGPer100g: 0, fatGPer100g: 3.6,
    fiberGPer100g: 0, vitaminB12UgPer100g: 0.3, ironMgPer100g: 0.7,
    giIndex: 0, defaultPortionG: 100, defaultPortionDesc: '1 medium piece',
    mealSlots: ['lunch', 'dinner'],
    purineLevel: 1,
    diseaseAllowed: ['diabetes_t2', 'weight_loss', 'muscle_gain'],
    diseaseRestricted: ['gout'],
    costTier: 'standard', prepTimeMin: 25,
    source: 'IFCT-2017',
  },
  // BEVERAGES
  {
    id: 'food-green-tea',
    name: 'Green Tea (brewed, unsweetened)',
    category: 'BEVERAGE',
    vegType: 'VEGAN',
    kcalPer100g: 1, proteinGPer100g: 0, carbGPer100g: 0.2, fatGPer100g: 0,
    fiberGPer100g: 0,
    giIndex: 0, defaultPortionG: 240, defaultPortionDesc: '1 cup',
    mealSlots: ['early_morning', 'mid_morning', 'evening_snack'],
    diseaseAllowed: ['diabetes_t2', 'weight_loss', 'heart_health'],
    diseaseRestricted: ['gerd', 'anxiety', 'insomnia'],
    costTier: 'economy', prepTimeMin: 3,
    source: 'IFCT-2017',
  },
  {
    id: 'food-coconut-water',
    name: 'Coconut Water (fresh)',
    category: 'BEVERAGE',
    vegType: 'VEGAN',
    kcalPer100g: 19, proteinGPer100g: 0.7, carbGPer100g: 3.7, fatGPer100g: 0.2,
    fiberGPer100g: 1.1, potassiumMgPer100g: 250,
    giIndex: 55, defaultPortionG: 200, defaultPortionDesc: '1 medium glass',
    mealSlots: ['mid_morning', 'evening_snack'],
    diseaseAllowed: ['diarrhoea_recovery', 'hypertension', 'ckd_early'],
    diseaseRestricted: ['ckd_stage4', 'hyperkalemia'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
  // SPICES
  {
    id: 'food-turmeric',
    name: 'Turmeric (haldi)',
    category: 'SPICE',
    vegType: 'VEGAN',
    kcalPer100g: 354, proteinGPer100g: 7.8, carbGPer100g: 64.9, fatGPer100g: 9.9,
    fiberGPer100g: 21.1,
    giIndex: 0, defaultPortionG: 2, defaultPortionDesc: '1/4 tsp',
    mealSlots: ['breakfast', 'lunch', 'dinner', 'bedtime'],
    diseaseAllowed: ['arthritis', 'inflammation', 'diabetes_t2'],
    costTier: 'economy', prepTimeMin: 0,
    source: 'IFCT-2017',
  },
];

// ===================== RECIPES =====================
const RECIPES = [
  {
    id: 'recipe-dal-tadka',
    name: 'Dal Tadka (toor dal)',
    cuisine: 'north_indian',
    mealSlots: ['lunch', 'dinner'],
    vegType: 'VEGAN',
    prepTimeMin: 30,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 180,
    proteinGPerServing: 9,
    carbGPerServing: 28,
    fatGPerServing: 4,
    fiberGPerServing: 6,
    giEstimate: 25,
    tags: ['high-fiber', 'low-gi', 'high-protein'],
    conditionTags: ['diabetes_t2', 'weight_loss', 'heart_health'],
    costTier: 'economy',
  },
  {
    id: 'recipe-moong-dal-chilla',
    name: 'Moong Dal Chilla',
    cuisine: 'north_indian',
    mealSlots: ['breakfast', 'evening_snack'],
    vegType: 'VEGAN',
    prepTimeMin: 20,
    difficulty: 'easy',
    servingsBase: 2,
    kcalPerServing: 150,
    proteinGPerServing: 10,
    carbGPerServing: 20,
    fatGPerServing: 3,
    fiberGPerServing: 4,
    giEstimate: 30,
    tags: ['high-protein', 'low-gi', 'quick'],
    conditionTags: ['diabetes_t2', 'pcos', 'weight_loss'],
    costTier: 'economy',
  },
  {
    id: 'recipe-oatmeal-masala',
    name: 'Masala Oats (savory)',
    cuisine: 'fusion',
    mealSlots: ['breakfast'],
    vegType: 'VEGAN',
    prepTimeMin: 10,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 210,
    proteinGPerServing: 7,
    carbGPerServing: 35,
    fatGPerServing: 5,
    fiberGPerServing: 6,
    giEstimate: 50,
    tags: ['quick', 'high-fiber', 'heart-healthy'],
    conditionTags: ['diabetes_t2', 'heart_health', 'high_ldl', 'weight_loss'],
    costTier: 'standard',
  },
  {
    id: 'recipe-paneer-bhurji',
    name: 'Paneer Bhurji',
    cuisine: 'north_indian',
    mealSlots: ['breakfast', 'lunch', 'dinner'],
    vegType: 'VEG',
    prepTimeMin: 15,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 220,
    proteinGPerServing: 15,
    carbGPerServing: 5,
    fatGPerServing: 16,
    fiberGPerServing: 1,
    giEstimate: 20,
    tags: ['high-protein', 'keto-friendly', 'low-carb'],
    conditionTags: ['diabetes_t2', 'muscle_gain', 'weight_loss'],
    costTier: 'standard',
  },
  {
    id: 'recipe-idli-sambar',
    name: 'Idli with Sambar (2 idlis)',
    cuisine: 'south_indian',
    mealSlots: ['breakfast', 'lunch'],
    vegType: 'VEGAN',
    prepTimeMin: 20,
    difficulty: 'medium',
    servingsBase: 1,
    kcalPerServing: 280,
    proteinGPerServing: 10,
    carbGPerServing: 50,
    fatGPerServing: 3,
    fiberGPerServing: 5,
    giEstimate: 40,
    tags: ['fermented', 'probiotic', 'light'],
    conditionTags: ['general', 'weight_loss', 'pregnancy'],
    costTier: 'economy',
  },
  {
    id: 'recipe-palak-dal',
    name: 'Palak Dal (spinach lentil)',
    cuisine: 'north_indian',
    mealSlots: ['lunch', 'dinner'],
    vegType: 'VEGAN',
    prepTimeMin: 25,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 160,
    proteinGPerServing: 10,
    carbGPerServing: 22,
    fatGPerServing: 3,
    fiberGPerServing: 8,
    giEstimate: 22,
    tags: ['iron-rich', 'folate-rich', 'high-fiber'],
    conditionTags: ['anaemia', 'pregnancy', 'weight_loss'],
    costTier: 'economy',
  },
  {
    id: 'recipe-egg-bhurji',
    name: 'Egg Bhurji (scrambled spiced)',
    cuisine: 'north_indian',
    mealSlots: ['breakfast', 'dinner'],
    vegType: 'EGG',
    prepTimeMin: 10,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 190,
    proteinGPerServing: 13,
    carbGPerServing: 5,
    fatGPerServing: 13,
    fiberGPerServing: 1,
    giEstimate: 15,
    tags: ['high-protein', 'quick', 'low-carb'],
    conditionTags: ['diabetes_t2', 'weight_loss', 'muscle_gain'],
    costTier: 'economy',
  },
  {
    id: 'recipe-chicken-soup',
    name: 'Clear Chicken Soup',
    cuisine: 'general',
    mealSlots: ['lunch', 'dinner'],
    vegType: 'NON_VEG',
    prepTimeMin: 35,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 120,
    proteinGPerServing: 18,
    carbGPerServing: 4,
    fatGPerServing: 3,
    fiberGPerServing: 1,
    giEstimate: 15,
    tags: ['low-calorie', 'high-protein', 'light'],
    conditionTags: ['weight_loss', 'recovery', 'elderly'],
    costTier: 'standard',
  },
  {
    id: 'recipe-raita',
    name: 'Cucumber Raita',
    cuisine: 'north_indian',
    mealSlots: ['lunch', 'dinner'],
    vegType: 'VEG',
    prepTimeMin: 5,
    difficulty: 'easy',
    servingsBase: 1,
    kcalPerServing: 60,
    proteinGPerServing: 3,
    carbGPerServing: 7,
    fatGPerServing: 2,
    fiberGPerServing: 1,
    giEstimate: 30,
    tags: ['probiotic', 'cooling', 'low-calorie'],
    conditionTags: ['diabetes_t2', 'ibs_d', 'pitta'],
    costTier: 'economy',
  },
  {
    id: 'recipe-bajra-roti',
    name: 'Bajra Roti (pearl millet flatbread)',
    cuisine: 'rajasthani',
    mealSlots: ['dinner', 'breakfast'],
    vegType: 'VEGAN',
    prepTimeMin: 15,
    difficulty: 'medium',
    servingsBase: 2,
    kcalPerServing: 120,
    proteinGPerServing: 4,
    carbGPerServing: 22,
    fatGPerServing: 2,
    fiberGPerServing: 3,
    giEstimate: 55,
    tags: ['gluten-free', 'iron-rich', 'winter-food'],
    conditionTags: ['anaemia', 'diabetes_t2', 'pcos'],
    costTier: 'economy',
  },
];

// ===================== FOOD SUBSTITUTIONS =====================
const SUBSTITUTIONS = [
  // White rice → brown rice (diabetes)
  { fromFoodId: 'food-rice-raw', toFoodId: 'food-brown-rice', contextSlot: null, reason: 'lower_gi_diabetes', similarityScore: 0.85 },
  // Potato → sweet potato (diabetes)
  { fromFoodId: 'food-potato', toFoodId: 'food-sweet-potato', contextSlot: null, reason: 'lower_gi_diabetes', similarityScore: 0.7 },
  // White rice → bajra (diabetes + anaemia)
  { fromFoodId: 'food-rice-raw', toFoodId: 'food-bajra', contextSlot: 'dinner', reason: 'lower_gi_high_iron', similarityScore: 0.65 },
  // Paneer → egg (lactose intolerant, non-veg allowed)
  { fromFoodId: 'food-paneer', toFoodId: 'food-egg', contextSlot: null, reason: 'lactose_intolerance', similarityScore: 0.75 },
  // Paneer → chickpeas (vegan swap)
  { fromFoodId: 'food-paneer', toFoodId: 'food-chickpeas', contextSlot: null, reason: 'vegan_swap', similarityScore: 0.6 },
  // Toor dal → moong dal (FODMAP / IBS)
  { fromFoodId: 'food-toor-dal', toFoodId: 'food-moong-dal', contextSlot: null, reason: 'low_fodmap', similarityScore: 0.9 },
  // Spinach → broccoli (oxalate restriction)
  { fromFoodId: 'food-spinach', toFoodId: 'food-broccoli', contextSlot: null, reason: 'low_oxalate', similarityScore: 0.7 },
  // Sunflower oil → ghee (keto / sattvic)
  { fromFoodId: 'food-sunflower-oil', toFoodId: 'food-ghee', contextSlot: null, reason: 'sattvic_preference', similarityScore: 0.6 },
  // Milk → curd (lactose sensitive — fermented is tolerated)
  { fromFoodId: 'food-milk-toned', toFoodId: 'food-curd', contextSlot: null, reason: 'lactose_sensitivity', similarityScore: 0.8 },
  // Chicken → egg (budget / preference)
  { fromFoodId: 'food-chicken-breast', toFoodId: 'food-egg', contextSlot: null, reason: 'budget_economy', similarityScore: 0.75 },
  // Banana → guava (diabetes — lower GI)
  { fromFoodId: 'food-banana', toFoodId: 'food-guava', contextSlot: null, reason: 'lower_gi_diabetes', similarityScore: 0.7 },
  // Apple → guava (regional / seasonal)
  { fromFoodId: 'food-apple', toFoodId: 'food-guava', contextSlot: null, reason: 'regional_seasonal', similarityScore: 0.75 },
  // Oats → moong dal chilla (no oats preference)
  { fromFoodId: 'food-oats', toFoodId: 'food-moong-dal', contextSlot: 'breakfast', reason: 'regional_preference', similarityScore: 0.65 },
  // Wheat atta → bajra (gluten sensitive / PCOS)
  { fromFoodId: 'food-wheat-atta', toFoodId: 'food-bajra', contextSlot: null, reason: 'gluten_sensitive', similarityScore: 0.7 },
];

async function main() {
  console.log('🥗 Seeding Magic Diet data...');

  // ---- Foods ----
  let foodCount = 0;
  for (const food of FOODS) {
    await (prisma as any).food.upsert({
      where: { id: food.id },
      update: {},
      create: food,
    });
    foodCount++;
  }
  console.log(`✅ Seeded ${foodCount} foods`);

  // ---- Recipes ----
  let recipeCount = 0;
  for (const recipe of RECIPES) {
    await (prisma as any).recipe.upsert({
      where: { id: recipe.id },
      update: {},
      create: recipe,
    });
    recipeCount++;
  }
  console.log(`✅ Seeded ${recipeCount} recipes`);

  // ---- Substitutions ----
  let subCount = 0;
  for (const sub of SUBSTITUTIONS) {
    // Upsert by composite key — use createMany/upsert workaround for MariaDB
    const existing = await (prisma as any).foodSubstitution.findFirst({
      where: { fromFoodId: sub.fromFoodId, toFoodId: sub.toFoodId, contextSlot: sub.contextSlot ?? null },
    });
    if (!existing) {
      await (prisma as any).foodSubstitution.create({ data: sub });
      subCount++;
    }
  }
  console.log(`✅ Seeded ${subCount} food substitutions`);

  console.log('\n🎉 Magic Diet seed complete!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
